name: running scripts

on: 
  push:
  pull_request: 
    types: [closed, assigned, opened ,reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
    - name: display files
        run: |
           echo $GITHUB_SHA
           echo $GITHUB_REPOSITORY
           echo $GITHUB_WORKSPACE
           echo "${{ github.token }}"
           pwd
           ls -a
    - name: multiline script
      run: |
        node -v
        npm -v

    
