name: shell commamnds

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print a string
        run: echo " my name is sasank "
      
      - name: multiline script
        run: |
          node -v
          npm -v

      - name: python commamnds
        run: |
          import platform
          print(platform.processor())
        shell: python
